/**
 * Blockchain service — reads/writes the TantuveRegistry contract on Polygon Amoy.
 *
 * Uses ethers.js v6 directly. The contract ABI + address are loaded from
 * src/lib/contract.json (generated by the deploy script). If the file doesn't
 * exist yet, functions gracefully return null / skip the on-chain call.
 */

import { ethers, JsonRpcProvider, Wallet, Contract } from "ethers";

// ---------------------------------------------------------------------------
// Lazy-initialised provider + signer (server-side only)
// ---------------------------------------------------------------------------

let _provider: JsonRpcProvider | null = null;
let _signer: Wallet | null = null;

function getRpcUrl(): string {
  const key = process.env["ALCHEMY_API_KEY"];
  if (!key) throw new Error("ALCHEMY_API_KEY is not set");
  return `https://polygon-amoy.g.alchemy.com/v2/${key}`;
}

function getPrivateKey(): string {
  const pk = process.env["PRIVATE_KEY"];
  if (!pk) throw new Error("PRIVATE_KEY is not set");
  return pk;
}

export function getProvider(): JsonRpcProvider {
  if (!_provider) _provider = new JsonRpcProvider(getRpcUrl());
  return _provider;
}

export function getSigner(): Wallet {
  if (!_signer) _signer = new Wallet(getPrivateKey(), getProvider());
  return _signer;
}

// ---------------------------------------------------------------------------
// Contract helpers
// ---------------------------------------------------------------------------

let _contractArtifact: { address: string; abi: ethers.InterfaceAbi } | null = null;

async function loadArtifact() {
  if (_contractArtifact) return _contractArtifact;
  try {
    // Dynamic import — this file is generated by the deploy script
    const mod = await import("@/lib/contract.json");
    _contractArtifact = (mod as any).default ?? mod;
    return _contractArtifact;
  } catch {
    return null;
  }
}

export async function getContract(): Promise<Contract | null> {
  const artifact = await loadArtifact();
  if (!artifact) return null;
  return new Contract(artifact.address, artifact.abi, getSigner());
}

export async function getReadOnlyContract(): Promise<Contract | null> {
  const artifact = await loadArtifact();
  if (!artifact) return null;
  return new Contract(artifact.address, artifact.abi, getProvider());
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export type OnChainRecord = {
  ledgerHash: string;
  timestamp: number;
  writer: string;
  exists: boolean;
};

/**
 * Read a product's on-chain record. Returns null if no contract is deployed.
 */
export async function getOnChainRecord(
  productId: string,
): Promise<OnChainRecord | null> {
  const contract = await getReadOnlyContract();
  if (!contract) return null;
  try {
    const [ledgerHash, timestamp, writer, exists] =
      await contract.getProduct(productId);
    return {
      ledgerHash: ledgerHash as string,
      timestamp: Number(timestamp),
      writer: writer as string,
      exists: exists as boolean,
    };
  } catch (err) {
    console.error(`[blockchain] Failed to read on-chain record for ${productId}:`, err);
    return null;
  }
}

/**
 * Write a product's final ledger hash to the contract.
 * Returns the transaction hash, or null if the contract isn't deployed.
 */
export async function registerOnChain(
  productId: string,
  ledgerHash: string,
): Promise<string | null> {
  const contract = await getContract();
  if (!contract) return null;

  // Convert hex string to bytes32
  const bytes32Hash = ethers.zeroPadValue(
    ledgerHash.startsWith("0x") ? ledgerHash : `0x${ledgerHash}`,
    32,
  );

  console.log(`[blockchain] Registering ${productId} with hash ${bytes32Hash}`);

  const tx = await contract.registerProduct(productId, bytes32Hash);
  const receipt = await tx.wait();

  console.log(`[blockchain] Tx confirmed: ${receipt.hash}`);
  return receipt.hash as string;
}

/**
 * Check if the Alchemy RPC is reachable.
 */
export async function checkAlchemyConnection(): Promise<boolean> {
  try {
    const provider = getProvider();
    await provider.getBlockNumber();
    return true;
  } catch {
    return false;
  }
}
